[#50] SVG 추가 테스트
SeokHoChoi/allini pull request #51
Opened 2024-10-03 12:55 UTC by SeokHoChoi

**개발 사항**
- SVG를 컴포넌트처럼 사용하기 위한 svgr/webpack 설정 추가
  - 직접 SVG를 컴포넌트로 만드는 방식보다 명확한 구분을 위해. svg 확장자가 보이도록 개발
- declarations.d.ts에 SVG 관련 타입 설정 추가
- 편의를 위한 assets 관련 절대 경로 추가 (@assets/..)

**문제 해결**
- svgr/webpack과 asset/resource의 규칙 충돌 해결

**해결해야 할 과제**
현재 개발한 <Svg /> 방식에서는 props를 넘길 수 없어 에러가 발생하고 있습니다. 타입 설정을 추가해도 해결되지 않으며, Next.js 등 다른 프레임워크에서는 잘 동작하는 것으로 보입니다.

특히, <Svg width="24" /> 형태로 사용하고 싶지만, 현재는 CSS에서 직접적으로 svg { }에 설정하고 있어 유연성이 떨어진다고 생각합니다.

이 문제를 해결하기 위해서는 SVG 컴포넌트에서 props를 올바르게 처리할 수 있도록 타입과 SVGR 설정을 다시 점검 중입니다.

2024-10-03 13:08 UTC, dante01yoon reviewed
> 현재 개발한 방식에서는 props를 넘길 수 없어 에러가 발생하고 있습니다 

문제 발생 화면과 예시 코드를 같이 첨부해주실 수 있을까요?

2024-10-03 13:19 UTC, SeokHoChoi commented
> > 현재 개발한 방식에서는 props를 넘길 수 없어 에러가 발생하고 있습니다
> 
> 문제 발생 화면과 예시 코드를 같이 첨부해주실 수 있을까요?

<img width="928" alt="스크린샷 2024-10-03 오후 10 14 29" src="https://github.com/user-attachments/assets/d61be471-d50d-43a8-9e52-dffdaf964ebb">

SVG를 컴포넌트화한 다음 props 형식으로 넘겨주려 할 때 첨부된 이미지에서와 같은 타입 에러가 발생해 해결 중입니다!

2024-10-03 14:45 UTC, dante01yoon requested changes
![스크린샷 2024-10-03 오후 11 43 04](https://github.com/user-attachments/assets/79a9321d-c750-492c-885b-9a4b77a744d4)

[SVGR 문서](https://react-svgr.com/docs/webpack/#use-svgr-and-asset-svg-in-the-same-project)를 잘못 해석하신 것 같습니다.

`resourceQuery: /url/, // *.svg?url` 의 경우 문자열 형태로 타입이 선언되어야 하며 
?url이 붙여지지 않았을 경우에는 컴포넌트로 타입을 선언해야 합니다. 

따라서 declarations.d.ts 파일은 다음과 같이 수정되어야 합니다.

```
// ... 생략
declare module "*.svg?url" {
  const url: string;
  export default url;
}

declare module "*.svg" {
  import React = require("react");

  const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
  export default ReactComponent
}

```

2024-10-03 14:46 UTC, dante01yoon reviewed
다음주 멘토링에서 같이 확인해야 하는 사항 📓 
- npm vs pnpm
- node version manage with nvm
- upgrade react to 18.3.1

2024-10-03 22:03 UTC, SeokHoChoi commented
> ![스크린샷 2024-10-03 오후 11 43 04](https://private-user-images.githubusercontent.com/6510430/373299119-79a9321d-c750-492c-885b-9a4b77a744d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTMyOTYsIm5iZiI6MTcyNzk5Mjk5NiwicGF0aCI6Ii82NTEwNDMwLzM3MzI5OTExOS03OWE5MzIxZC1jNzUwLTQ5MmMtODg1Yi05YTRiNzdhNzQ0ZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMjIwMzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmFkN2Q5ODM2Y2IwMTczMjQyMWJkYzU1MjM5MjljZTEzNjk5ZmViOGFmOTAxNTNiODA5ODc0MDYzNjI0MDliYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zpXr9Nb997Ql9S5sjAeAsjMqtjpt3SDZ8xPSGmj3ZdM)
> 
> [SVGR 문서](https://react-svgr.com/docs/webpack/#use-svgr-and-asset-svg-in-the-same-project)를 잘못 해석하신 것 같습니다.
> 
> `resourceQuery: /url/, // *.svg?url` 의 경우 문자열 형태로 타입이 선언되어야 하며 ?url이 붙여지지 않았을 경우에는 컴포넌트로 타입을 선언해야 합니다.
> 
> 따라서 declarations.d.ts 파일은 다음과 같이 수정되어야 합니다.
> 
> ```
> // ... 생략
> declare module "*.svg?url" {
>   const url: string;
>   export default url;
> }
> 
> declare module "*.svg" {
>   import React = require("react");
> 
>   const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
>   export default ReactComponent
> }
> ```

말씀 감사합니다!!
재검토 후 변경사항 반영해 커밋했습니다!

2024-10-03 22:04 UTC, SeokHoChoi commented
> 다음주 멘토링에서 같이 확인해야 하는 사항 📓
> 
> * npm vs pnpm
> * node version manage with nvm
> * upgrade react to 18.3.1

넵! 검토해 보겠습니다! 
감사합니다!

2024-10-04 08:34 UTC, dante01yoon approved these changes
고생하셨습니다 :)

2024-10-04 12:29 UTC, merged